'use client'

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default function TermsAndConditions() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1 container py-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold mb-4 text-[#005596]">Terms and Conditions</h1>
            <p className="text-lg text-gray-600 dark:text-gray-300">
              Please read these terms and conditions carefully before using our platform
            </p>
          </div>

          <Card>
            <CardHeader>
              <CardTitle className="text-2xl text-[#005596]">Terms and Conditions</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6 text-gray-700 dark:text-gray-300">
              <div className="space-y-4">
                <p>
                  This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>

                <p>
                  This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://chooseyourcollege.com/, including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                </p>

                <p>
                  The Platform is owned by Happi Global Ventures LLP, a company incorporated under the Companies Act, 1956 with its registered office at Innov8 Mantri Commercio MIS Deeta, Cnst, No 51 Bellandur, South Karnataka 560103, Bangalore (hereinafter referred to as "Platform Owner", 'we', 'us', 'our').
                </p>

                <p>
                  Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.
                </p>
              </div>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold text-[#005596] mt-8 mb-4">Key Terms</h2>
                <div className="space-y-3">
                  <p>
                    For the purpose of these Terms of Use, wherever the context so requires "you", 'your' or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                  </p>
                  <p>
                    To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
                  </p>
                  <p>
                    Payments made for the Services offered on this Platform are non-refundable. Once a transaction is processed, no refund requests will be entertained under any circumstances.
                  </p>
                  <p>
                    Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.
                  </p>
                </div>
              </div>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold text-[#005596] mt-8 mb-4">Intellectual Property</h2>
                <p>
                  The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.
                </p>
              </div>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold text-[#005596] mt-8 mb-4">Legal Jurisdiction</h2>
                <div className="space-y-3">
                  <p>
                    These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
                  </p>
                  <p>
                    All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bangalore and Karnataka.
                  </p>
                </div>
              </div>

              <div className="space-y-4">
                <h2 className="text-xl font-semibold text-[#005596] mt-8 mb-4">Contact</h2>
                <p>
                  All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
                </p>
              </div>

              <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Last updated: {new Date().toLocaleDateString('en-US', { 
                    year: 'numeric', 
                    month: 'long', 
                    day: 'numeric' 
                  })}
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <Footer />
    </div>
  )
} 