// Auto-generated Data Transparency classification for TN engineering colleges.
// Derived from the three NIRF source lists (all TN colleges, NIRF-participated, data-on-website)
// cross-referenced with TNEA counselling codes.
//
// Classification:
//   Transparent (green)  = government college, or NIRF data published on its website
//   Suspicious  (yellow) = participated in NIRF but data NOT published on website
//   Avoid       (red)    = never participated in NIRF
//
// To correct a specific college, edit its "t" value below: 'Transparent' | 'Suspicious' | 'Avoid'.

export type Transparency = 'Transparent' | 'Suspicious' | 'Avoid'

export interface TransparencyRow {
  code: string   // TNEA counselling code
  name: string
  t: Transparency
}

export const TRANSPARENCY_COUNTS = {"Transparent":226,"Avoid":176,"Suspicious":66} as const

export const TRANSPARENCY_ROWS: TransparencyRow[] = [
  {"code":"1","name":"University Departments of Anna University","t":"Transparent"},
  {"code":"2","name":"University Departments of Anna University","t":"Transparent"},
  {"code":"3","name":"School of Architecture and Planning","t":"Transparent"},
  {"code":"4","name":"University Departments of Anna University","t":"Transparent"},
  {"code":"5","name":"Annamalai University Faculty of Engineering and Technology","t":"Transparent"},
  {"code":"1013","name":"University College of Engineering","t":"Transparent"},
  {"code":"1014","name":"University College of Engineering","t":"Transparent"},
  {"code":"1015","name":"University College of Engineering","t":"Transparent"},
  {"code":"1026","name":"University College of Engineering","t":"Transparent"},
  {"code":"1101","name":"Aalim Muhammed Salegh College of Engineering","t":"Suspicious"},
  {"code":"1102","name":"Bhajarang Engineering College","t":"Avoid"},
  {"code":"1106","name":"Jaya Engineering College","t":"Transparent"},
  {"code":"1107","name":"Jaya Institute of Technology","t":"Transparent"},
  {"code":"1110","name":"Prathyusha Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"1112","name":"R.M.D. Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1113","name":"R.M.K. Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1114","name":"S.A. Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1115","name":"SriRam Engineering College","t":"Transparent"},
  {"code":"1116","name":"Sri Venkateswara College of Engineering and Technology","t":"Transparent"},
  {"code":"1118","name":"Vel Tech Multi Tech Dr Rangarajan Dr Sakunthala Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1120","name":"Velammal Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"1121","name":"Sri Venkateswara Institute of Science and Technology","t":"Avoid"},
  {"code":"1122","name":"Vel Tech High Tech Dr.Rangarajan Dr.Sakunthala Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"1123","name":"Gojan School of Business and Technology","t":"Transparent"},
  {"code":"1124","name":"SAMS College of Engineering and Technology","t":"Avoid"},
  {"code":"1125","name":"PMR Engineering College","t":"Avoid"},
  {"code":"1126","name":"J N N Institute of Engineering Ushaa Garden Kannigaipair","t":"Avoid"},
  {"code":"1127","name":"St. Peter's College of Engineering and Technology(Autonomous)","t":"Transparent"},
  {"code":"1128","name":"R.M.K. College of Engineering and Technology (Autonomous)","t":"Avoid"},
  {"code":"1133","name":"Annai Veilankannis College of Engineering","t":"Avoid"},
  {"code":"1137","name":"Annai Mira College of Engineering and Technology","t":"Avoid"},
  {"code":"1140","name":"Jeppiaar Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"1149","name":"St. Joseph's Institute of Technology (Autonomous)","t":"Suspicious"},
  {"code":"1150","name":"Sri Jayaram Institute of Engineering and Technology","t":"Suspicious"},
  {"code":"1158","name":"International Maritime Academy","t":"Suspicious"},
  {"code":"1202","name":"DMI College of Engineering (Autonomous)","t":"Suspicious"},
  {"code":"1203","name":"MADRAS ENGINEERING COLLEGE","t":"Avoid"},
  {"code":"1205","name":"Lord Venkateshwaraa Engineering College","t":"Avoid"},
  {"code":"1207","name":"Kings Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"1209","name":"Pallavan College of Engineering","t":"Avoid"},
  {"code":"1210","name":"Panimalar Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1211","name":"Rajalakshmi Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1212","name":"Rajiv Gandhi College of Engineering","t":"Transparent"},
  {"code":"1213","name":"S K R Engineering College","t":"Suspicious"},
  {"code":"1216","name":"Saveetha Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1217","name":"Sree Sastha Institute of Engineering and Technology","t":"Transparent"},
  {"code":"1218","name":"Sri Muthukumaran Institute of Technology","t":"Suspicious"},
  {"code":"1219","name":"Sri Venkateswara College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"1221","name":"Jaya College of Engineering and Technology","t":"Transparent"},
  {"code":"1222","name":"P.B. College of Engineering","t":"Avoid"},
  {"code":"1225","name":"Loyola Institute of Technology","t":"Transparent"},
  {"code":"1226","name":"P T Lee Chengalvaraya Naicker College of Engineering and Technology","t":"Avoid"},
  {"code":"1228","name":"Alpha College of Engineering","t":"Avoid"},
  {"code":"1229","name":"Indira Institute of Engineering and Technology","t":"Avoid"},
  {"code":"1230","name":"Apollo Engineering College","t":"Avoid"},
  {"code":"1231","name":"Panimalar Institute of Technology","t":"Avoid"},
  {"code":"1232","name":"ARM College of Engineering and Technology","t":"Avoid"},
  {"code":"1233","name":"Adhi College of Engineering and Technology","t":"Transparent"},
  {"code":"1235","name":"Jei Mathaajee College of Engineering","t":"Avoid"},
  {"code":"1237","name":"Velammal Institute of Technology","t":"Transparent"},
  {"code":"1238","name":"G R T Institute of Engineering and Technology","t":"Transparent"},
  {"code":"1241","name":"T J S Engineering College","t":"Transparent"},
  {"code":"1243","name":"ST. LOURDES ENGINEERING COLLEGE (Formerly Madha Institute of Engineering and Technology)","t":"Avoid"},
  {"code":"1301","name":"Mohamed Sathak A J College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"1303","name":"Anand Institute of Higher Technology","t":"Transparent"},
  {"code":"1304","name":"Easwari Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1306","name":"Jeppiaar Engineering College","t":"Transparent"},
  {"code":"1307","name":"Jerusalem College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"1309","name":"Meenakshi Sundararajan Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1310","name":"Misrimal Navajee Munoth Jain Engineering College","t":"Transparent"},
  {"code":"1311","name":"KCG college of Technology (Autonomous)","t":"Transparent"},
  {"code":"1313","name":"Shree Motilal Kanhaiyalal (SMK)Fomra Institute of Technology","t":"Avoid"},
  {"code":"1315","name":"Sri Sivasubramaniya Nadar College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"1316","name":"Agni College of Technology (Autonomous)","t":"Transparent"},
  {"code":"1317","name":"St. Joseph's College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"1318","name":"T.J. Institute of Technology","t":"Transparent"},
  {"code":"1319","name":"Thangavelu Engineering College","t":"Transparent"},
  {"code":"1321","name":"Central Institute of Petrochemicals Engineering and Technology (Formerly Central Institute of Plastics Engineering and Technology) (CIPET)","t":"Avoid"},
  {"code":"1322","name":"Dhanalakshmi Srinivasan College of Engineering and Technology","t":"Transparent"},
  {"code":"1324","name":"Sri Sai Ram Institute of Technology (Autonomous)","t":"Suspicious"},
  {"code":"1325","name":"St. Joseph College of Engineering","t":"Transparent"},
  {"code":"1333","name":"Shikshaa Institute of Advanced Technologies (formerly Vi Institute of Technology)","t":"Avoid"},
  {"code":"1334","name":"ARS College of Engineering","t":"Avoid"},
  {"code":"1335","name":"Sri Krishna Institute of Technology","t":"Suspicious"},
  {"code":"1339","name":"MAHALAKSHMI TECH CAMPUS (FORMERLY MAHALAKSHMI ENGINEERING COLLEGE - TIRUCHIRAPPALLI)","t":"Avoid"},
  {"code":"1398","name":"Chennai Institute of Technology and Applied Research Sarathy Nagar Puthuper","t":"Avoid"},
  {"code":"1399","name":"Chennai Institute of Technology (Autonomous) Puduper","t":"Transparent"},
  {"code":"1400","name":"Mohamed Sathak A.J. Academy of Architecture","t":"Avoid"},
  {"code":"1401","name":"Adhiparasakthi Engineering College","t":"Transparent"},
  {"code":"1402","name":"Annai Teresa College of Engineering","t":"Avoid"},
  {"code":"1405","name":"Dhanalakshmi College of Engineering","t":"Transparent"},
  {"code":"1407","name":"G K M College of Engineering and Technology","t":"Transparent"},
  {"code":"1408","name":"IFET College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"1409","name":"Karpaga Vinayaga College of Engineering and Technology","t":"Transparent"},
  {"code":"1411","name":"Madha Engineering College","t":"Transparent"},
  {"code":"1412","name":"Mailam Engineering College","t":"Transparent"},
  {"code":"1413","name":"Sri Venkateswaraa College of Technology","t":"Transparent"},
  {"code":"1414","name":"Prince Shri Venkateshwaraa Padmavathy Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"1415","name":"T.S.M.Jain College of Technology","t":"Avoid"},
  {"code":"1416","name":"Jaya Sakthi Engineering College","t":"Avoid"},
  {"code":"1419","name":"Sri Sai Ram Engineering College (Autonomous)","t":"Avoid"},
  {"code":"1420","name":"Tagore Engineering College","t":"Transparent"},
  {"code":"1421","name":"V.R.S. College of Engineering and Technology","t":"Suspicious"},
  {"code":"1422","name":"SRM Valliammai Engineering College (Autonomous)","t":"Transparent"},
  {"code":"1423","name":"Asan Memorial College of Engineering and Technology","t":"Transparent"},
  {"code":"1424","name":"Dhaanish Ahmed College of Engineering","t":"Transparent"},
  {"code":"1426","name":"Sri Ramanujar Engineering College","t":"Avoid"},
  {"code":"1427","name":"Sri Krishna Engineering College","t":"Transparent"},
  {"code":"1428","name":"Quannta School of Software Engineering (formerly E S Engineering College)","t":"Avoid"},
  {"code":"1430","name":"Maha Barathi Engineering College","t":"Avoid"},
  {"code":"1431","name":"New Prince Shri Bhavani College of Engineering and Technology (Autonomous)","t":"Suspicious"},
  {"code":"1432","name":"Rajalakshmi Institute of Technology (Autonomous) Irulapalayam Kuthampakkam","t":"Transparent"},
  {"code":"1434","name":"Surya Group of Institutions","t":"Avoid"},
  {"code":"1435","name":"Jagannath Institute of Technology","t":"Avoid"},
  {"code":"1436","name":"A R Engineering College","t":"Avoid"},
  {"code":"1437","name":"Rrase College of Engineering","t":"Transparent"},
  {"code":"1438","name":"Sree Krishna College of Engineering","t":"Avoid"},
  {"code":"1441","name":"A.K.T.Memorial College of Engineering and Technology","t":"Transparent"},
  {"code":"1442","name":"Prince Dr. K. Vasudevan College of Engineering and Technology (Autonomous)","t":"Suspicious"},
  {"code":"1444","name":"R.M.Engineering College (formerly Chendu College of Engineering and Technology)","t":"Avoid"},
  {"code":"1445","name":"Sri Rangapoopathi College of Engineering","t":"Avoid"},
  {"code":"1447","name":"Jawahar Engineering College","t":"Avoid"},
  {"code":"1449","name":"Saraswathy College of Engineering and Technology","t":"Avoid"},
  {"code":"1450","name":"Loyola ICAM College of Engineering and Technology","t":"Transparent"},
  {"code":"1452","name":"PERI Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"1501","name":"Adhiparasakthi College of Engineering","t":"Avoid"},
  {"code":"1503","name":"Arulmigu Meenakshi Amman College of Engineering","t":"Transparent"},
  {"code":"1504","name":"Arunai Engineering College (Autonomous)","t":"Avoid"},
  {"code":"1505","name":"C.Abdul Hakeem College of Engineering and Technology","t":"Suspicious"},
  {"code":"1507","name":"Ganadipathy Tulsi's Jain Engineering College","t":"Suspicious"},
  {"code":"1509","name":"Meenakshi College of Engineering","t":"Transparent"},
  {"code":"1510","name":"Priyadarshini Engineering College","t":"Transparent"},
  {"code":"1511","name":"RANIPPETTAI ENGINEERING COLLEGE","t":"Avoid"},
  {"code":"1512","name":"S.K.P. Engineering College","t":"Avoid"},
  {"code":"1513","name":"Sri Balaji Chockalingam Engineering College","t":"Avoid"},
  {"code":"1514","name":"Sri Nandhanam College of Engineering and Technology","t":"Avoid"},
  {"code":"1516","name":"Thanthai Periyar Government Institute of Technology","t":"Transparent"},
  {"code":"1517","name":"Thirumalai Engineering College","t":"Avoid"},
  {"code":"1518","name":"Thiruvalluvar College of Engineering and Technology","t":"Suspicious"},
  {"code":"1519","name":"Bharathidasan Engineering College","t":"Transparent"},
  {"code":"1520","name":"Kingston Engineering College","t":"Avoid"},
  {"code":"1523","name":"Global Institute of Engineering and Technology","t":"Transparent"},
  {"code":"1524","name":"Annamalaiar College Of Engineering","t":"Transparent"},
  {"code":"1525","name":"Podhigai College of Engineering and Technology","t":"Avoid"},
  {"code":"1526","name":"Sri Krishna College of Engineering","t":"Avoid"},
  {"code":"1529","name":"Oxford College of Engineering","t":"Transparent"},
  {"code":"1533","name":"Panimalar Engineering College Chennai City Campus","t":"Avoid"},
  {"code":"1605","name":"Idhaya Engineering College for Women","t":"Transparent"},
  {"code":"2005","name":"Government College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2006","name":"PSG College of Technology (Autonomous)","t":"Suspicious"},
  {"code":"2007","name":"Coimbatore Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2025","name":"Anna University Regional Campus - Coimbatore","t":"Transparent"},
  {"code":"2302","name":"Sri Shanmugha College of Engineering and Technology (Autonomous)","t":"Suspicious"},
  {"code":"2314","name":"Muthayammal College of Engineering","t":"Transparent"},
  {"code":"2327","name":"N.S.N. College of Engineering and Technology","t":"Suspicious"},
  {"code":"2328","name":"K S R Institute for Engineering and Technology (Autonomous) Thokkavadi Namakkal","t":"Transparent"},
  {"code":"2329","name":"Rathinam Technical Campus (Autonomous)","t":"Transparent"},
  {"code":"2332","name":"Aishwarya College of Engineering and Technology","t":"Avoid"},
  {"code":"2338","name":"Asian College of Engineering and Technology","t":"Transparent"},
  {"code":"2341","name":"Ganesh College of Engineering","t":"Avoid"},
  {"code":"2342","name":"Sri Ranganathar Institute of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2343","name":"Indian Institute of Handloom Technology","t":"Avoid"},
  {"code":"2345","name":"Dhirajlal Gandhi College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2346","name":"Shree Sathyam College of Engineering and Technology","t":"Avoid"},
  {"code":"2347","name":"AVS College of Technology","t":"Transparent"},
  {"code":"2349","name":"Dhaanish Ahmed Institute of Technology","t":"Transparent"},
  {"code":"2350","name":"Jairupaa College of Engineering","t":"Avoid"},
  {"code":"2354","name":"Pollachi Institute of Engineering and Technology","t":"Avoid"},
  {"code":"2355","name":"Cheran College of Engineering","t":"Avoid"},
  {"code":"2356","name":"Arulmurugan College of Engineering","t":"Suspicious"},
  {"code":"2357","name":"V.S.B. College of Engineering Technical Campus (Autonomous)","t":"Transparent"},
  {"code":"2360","name":"Suguna College of Engineering","t":"Avoid"},
  {"code":"2361","name":"SASI CREATIVE SCHOOL OF ARCHITECTURE","t":"Avoid"},
  {"code":"2367","name":"Arjun College of Technology","t":"Transparent"},
  {"code":"2368","name":"Vishnu Lakshmi College of Engineering and Technology","t":"Avoid"},
  {"code":"2369","name":"Government College of Engineering","t":"Transparent"},
  {"code":"2377","name":"PSG Institute of Technology and Applied Research(Autonomous)","t":"Transparent"},
  {"code":"2378","name":"Cherraan College of Technology","t":"Avoid"},
  {"code":"2601","name":"Adhiyamaan College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"2602","name":"Annai Mathammal Sheela Engineering College","t":"Avoid"},
  {"code":"2603","name":"Government College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"2606","name":"Jayam College of Engineering and Technology","t":"Avoid"},
  {"code":"2607","name":"K S Rangasamy College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2608","name":"M.Kumarasamy College of Engineering (Autonomous)","t":"Suspicious"},
  {"code":"2609","name":"Mahendra Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"2610","name":"Muthayammal Engineering College (Autonomous)","t":"Avoid"},
  {"code":"2611","name":"Paavai Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2612","name":"PGP College of Engineering and Technology","t":"Avoid"},
  {"code":"2613","name":"K S R College of Engineering (Autonomous)","t":"Avoid"},
  {"code":"2614","name":"SSM College of Engineering","t":"Transparent"},
  {"code":"2615","name":"Government College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"2616","name":"Sapthagiri College of Engineering","t":"Avoid"},
  {"code":"2617","name":"Sengunthar Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2618","name":"Sona College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2620","name":"Vivekanandha College of Engineering for Women (Autonomous)","t":"Transparent"},
  {"code":"2621","name":"Er. Perumal Manimekalai College of Engineering (Autonomous)","t":"Suspicious"},
  {"code":"2622","name":"V S B Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2623","name":"Mahendra College of Engineering","t":"Transparent"},
  {"code":"2624","name":"Gnanamani College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2625","name":"The Kavery Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"2627","name":"Selvam College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2628","name":"Paavai College of Engineering","t":"Avoid"},
  {"code":"2629","name":"Sengunthar College of Engineering","t":"Avoid"},
  {"code":"2630","name":"Chettinad College of Engineering and Technology","t":"Transparent"},
  {"code":"2632","name":"Mahendra Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2633","name":"Vidyaa Vikas College of Engineering and Technology","t":"Avoid"},
  {"code":"2634","name":"Excel Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2635","name":"CMS College of Engineering","t":"Avoid"},
  {"code":"2636","name":"A V S Engineering College","t":"Avoid"},
  {"code":"2638","name":"Mahendra Engineering College for Women","t":"Avoid"},
  {"code":"2639","name":"Narasu's Sarathy Institute of Technology","t":"Transparent"},
  {"code":"2640","name":"Jayalakshmi Institute of Technology","t":"Avoid"},
  {"code":"2641","name":"Varuvan Vadivelan Institute of Technology","t":"Avoid"},
  {"code":"2642","name":"P S V College of Engineeering and Technology","t":"Transparent"},
  {"code":"2643","name":"Bharathiyar Institute of Engineering for Women","t":"Transparent"},
  {"code":"2646","name":"Tagore Institute of Engineering and Technology","t":"Transparent"},
  {"code":"2647","name":"J.K.K.Nataraja College of Engineering and Technology","t":"Avoid"},
  {"code":"2648","name":"Annapoorana Engineering College (Autonomous)","t":"Avoid"},
  {"code":"2650","name":"Christ The King Engineering College","t":"Transparent"},
  {"code":"2651","name":"Jai Shriram Engineering College","t":"Suspicious"},
  {"code":"2652","name":"AL-Ameen Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2653","name":"Knowledge Institute of Technology (Autonomous) KIOT Campus Kakapalayam","t":"Transparent"},
  {"code":"2656","name":"Kangeyam Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2657","name":"Paavai College of Technology","t":"Avoid"},
  {"code":"2658","name":"V S A Group of Institutions","t":"Avoid"},
  {"code":"2659","name":"Salem College of Engineering and Technology","t":"Suspicious"},
  {"code":"2661","name":"Vivekanandha College of Technology for Women","t":"Avoid"},
  {"code":"2662","name":"Dr. Nagarathinams College of Engineering","t":"Avoid"},
  {"code":"2665","name":"Mahendra Institute of Engineering and Technology","t":"Avoid"},
  {"code":"2673","name":"Sree Sakthi Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2683","name":"Shreenivasa Engineering College","t":"Suspicious"},
  {"code":"2702","name":"Bannari Amman Institute of Technology (Autonomous)","t":"Avoid"},
  {"code":"2704","name":"Coimbatore Institute of Engineering and Technology (Autonomous)","t":"Avoid"},
  {"code":"2705","name":"CSI College of Engineering","t":"Transparent"},
  {"code":"2706","name":"Dr Mahalingam College of Engineering and Technology (Autonomous)","t":"Suspicious"},
  {"code":"2707","name":"Erode Sengunthar Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2708","name":"Hindusthan College of Engineering and Technology(Autonomous)","t":"Transparent"},
  {"code":"2709","name":"Government College of Engineering (Formerly Institute of Road and Transport Technology)","t":"Transparent"},
  {"code":"2710","name":"Karpagam College of Engineering (Autonomous)","t":"Suspicious"},
  {"code":"2711","name":"Kongu Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2712","name":"Kumaraguru College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2713","name":"M P Nachimuthu M Jaganathan Engineering College","t":"Suspicious"},
  {"code":"2715","name":"Nandha Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2716","name":"Park College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2717","name":"Sasurie College of Engineering","t":"Suspicious"},
  {"code":"2718","name":"Sri Krishna College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2719","name":"Sri Ramakrishna Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2721","name":"Tamilnadu College of Engineering","t":"Suspicious"},
  {"code":"2722","name":"Sri Krishna College of Technology (Autonomous)","t":"Avoid"},
  {"code":"2723","name":"Velalar College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2725","name":"Sri Ramakrishna Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2726","name":"SNS College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2727","name":"Sri Shakthi Institute of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2729","name":"Nehru Institute of Engineering and Technology (Autonomous)","t":"Suspicious"},
  {"code":"2731","name":"RVS College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2732","name":"Info Institute of Engineering","t":"Transparent"},
  {"code":"2733","name":"Angel College of Engineering and Technology","t":"Avoid"},
  {"code":"2734","name":"SNS College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"2735","name":"Karpagam Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2736","name":"Dr N.G.P. Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2737","name":"Sri Sai Ranganathan Engineering College","t":"Avoid"},
  {"code":"2739","name":"Sri Eshwar College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"2740","name":"Hindusthan Institute of Technology (Autonomous)","t":"Avoid"},
  {"code":"2741","name":"P A College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2743","name":"Dhanalakshmi Srinivasan College of Engineering (CBE)","t":"Avoid"},
  {"code":"2744","name":"Adithya Institute of Technology (Autonomous)","t":"Suspicious"},
  {"code":"2745","name":"Kathir College of Engineering (Autonomous)","t":"Suspicious"},
  {"code":"2747","name":"Shree Venkateshwara Hi-Tech Engineering College (Autonomous)","t":"Transparent"},
  {"code":"2748","name":"Surya Engineering College","t":"Suspicious"},
  {"code":"2749","name":"Easa College of Engineering and Technology","t":"Avoid"},
  {"code":"2750","name":"KIT - Kalaignarkarunanidhi Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2751","name":"KGISL Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2752","name":"Nandha College of Technology","t":"Transparent"},
  {"code":"2753","name":"PPG Institute of Technology","t":"Transparent"},
  {"code":"2755","name":"Nehru Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2758","name":"JKK Munirajah College of Technology (Autonomous)","t":"Transparent"},
  {"code":"2761","name":"United Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2762","name":"Jansons Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"2763","name":"Akshaya College of Engineering and Technology","t":"Transparent"},
  {"code":"2764","name":"KPR Institute of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2767","name":"SRG Engineering College","t":"Suspicious"},
  {"code":"2768","name":"Park College of Technology","t":"Avoid"},
  {"code":"2769","name":"JCT College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"2770","name":"Studyworld College of Engineering","t":"Avoid"},
  {"code":"2772","name":"C M S College of Engineering and Technology","t":"Avoid"},
  {"code":"2776","name":"R V S Technical Campus Coimbatore (Autonomous)","t":"Avoid"},
  {"code":"2777","name":"HINDUSTHAN COLLEGE OF ENGINEERING","t":"Avoid"},
  {"code":"3011","name":"University College of Engineering","t":"Transparent"},
  {"code":"3016","name":"University College of Engineering","t":"Transparent"},
  {"code":"3018","name":"University College of Engineering","t":"Transparent"},
  {"code":"3019","name":"University College of Engineering","t":"Transparent"},
  {"code":"3021","name":"University College of Engineering","t":"Transparent"},
  {"code":"3403","name":"Mahalakshmi Engineering College","t":"Suspicious"},
  {"code":"3410","name":"Krishnasamy College of Engineering and Technology","t":"Avoid"},
  {"code":"3425","name":"C.K. College of Engineering & Technology","t":"Transparent"},
  {"code":"3451","name":"SMR East Coast College of Engineering and Technology","t":"Avoid"},
  {"code":"3454","name":"Sri Ramakrishna College of Engineering","t":"Avoid"},
  {"code":"3456","name":"KSK College of Engineering and Technology","t":"Transparent"},
  {"code":"3460","name":"Surya College of Engineering","t":"Avoid"},
  {"code":"3461","name":"Arifa Institute of Technology(Formly Haji sheik Ismail Engineering College)","t":"Transparent"},
  {"code":"3462","name":"Ariyalur Engineering College","t":"Avoid"},
  {"code":"3464","name":"Government College of Engineering","t":"Transparent"},
  {"code":"3465","name":"Government College of Engineering","t":"Transparent"},
  {"code":"3466","name":"Nelliandavar Institute of Technology","t":"Avoid"},
  {"code":"3477","name":"SRI VIGNESH COLLEGE OF ENGINEERING AND TECHNOLOGY","t":"Avoid"},
  {"code":"3701","name":"K Ramakrishnan College of Technology (Autonomous)","t":"Transparent"},
  {"code":"3760","name":"Sir Issac Newton College of Engineering and Technology","t":"Transparent"},
  {"code":"3766","name":"Star Lion College of Engineering and Technology","t":"Transparent"},
  {"code":"3782","name":"OASYS Institute of Technology","t":"Avoid"},
  {"code":"3786","name":"M.A.M. School of Engineering (Autonomous)","t":"Transparent"},
  {"code":"3795","name":"SRM TRP Engineering College","t":"Transparent"},
  {"code":"3801","name":"A.V.C. College of Engineering","t":"Transparent"},
  {"code":"3802","name":"Shri Angalamman College of Engineering and Technology","t":"Avoid"},
  {"code":"3803","name":"Anjalai Ammal Mahalingam Engineering College","t":"Transparent"},
  {"code":"3804","name":"Arasu Engineering College","t":"Transparent"},
  {"code":"3805","name":"Dhanalakshmi Srinivasan Engineering College (Autonomous)","t":"Transparent"},
  {"code":"3806","name":"E.G.S. Pillay Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"3807","name":"J.J. College of Engineering and Technology","t":"Avoid"},
  {"code":"3808","name":"Jayaram College of Engineering and Technology","t":"Avoid"},
  {"code":"3809","name":"Kurinji College of Engineering and Technology","t":"Avoid"},
  {"code":"3810","name":"M A M College of Engineering","t":"Suspicious"},
  {"code":"3811","name":"M.I.E.T. Engineering College (Autonomous)","t":"Transparent"},
  {"code":"3812","name":"Mookambigai College of Engineering","t":"Avoid"},
  {"code":"3813","name":"Oxford Engineering College","t":"Avoid"},
  {"code":"3814","name":"P.R. Engineering College","t":"Suspicious"},
  {"code":"3815","name":"Pavendar Bharathidasan College of Engineering and Technology","t":"Avoid"},
  {"code":"3817","name":"Roever Engineering College","t":"Transparent"},
  {"code":"3819","name":"Saranathan College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"3820","name":"Trichy Engineering College","t":"Suspicious"},
  {"code":"3821","name":"A.R.J College of Engineering and Technology","t":"Avoid"},
  {"code":"3822","name":"Tittagudi Sengunthar Engineering College (Formerly Dr.Navalar Nedunchezhiyan College of Engineering)","t":"Avoid"},
  {"code":"3825","name":"St. Joseph's College of Engineering and Technology","t":"Transparent"},
  {"code":"3826","name":"Kongunadu College of Engineering and Technology (Autonomous)","t":"Suspicious"},
  {"code":"3829","name":"M.A.M. College of Engineering and Technology","t":"Avoid"},
  {"code":"3830","name":"K Ramakrishnan College of Engineering (Autonomous)","t":"Avoid"},
  {"code":"3831","name":"Indra Ganesan College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"3833","name":"Parisutham Institute of Technology and Science (Autonomous)","t":"Suspicious"},
  {"code":"3841","name":"CARE College of Engineering (Formerly C.A.R.E Group of Institutions)","t":"Transparent"},
  {"code":"3843","name":"M R K Institute of Technology","t":"Transparent"},
  {"code":"3844","name":"Shivani Engineering College","t":"Avoid"},
  {"code":"3845","name":"Imayam College of Engineering","t":"Transparent"},
  {"code":"3846","name":"Mother Terasa College of Engineering and Technology","t":"Transparent"},
  {"code":"3848","name":"Vandayar Engineering College","t":"Avoid"},
  {"code":"3849","name":"Annai College of Engineering and Technology","t":"Suspicious"},
  {"code":"3850","name":"Vetri Vinayaha College of Engineering and Technology","t":"Avoid"},
  {"code":"3852","name":"Sri Bharathi Engineering College for Women","t":"Suspicious"},
  {"code":"3854","name":"Mahath Amma Institute of Engineering and Technology","t":"Transparent"},
  {"code":"3855","name":"As-Salam College of Engineering and Technology","t":"Avoid"},
  {"code":"3857","name":"Meenakshi Ramaswamy Engineering College","t":"Avoid"},
  {"code":"3859","name":"Sembodai Rukmani Varatharajan Engineering College","t":"Avoid"},
  {"code":"3860","name":"St.Anne's College of Engineering and Technology","t":"Transparent"},
  {"code":"3905","name":"Kings College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"3908","name":"Mount Zion College of Engineering and Technology","t":"Transparent"},
  {"code":"3918","name":"Shanmuganathan Engineering College","t":"Avoid"},
  {"code":"3920","name":"Sudharsan Engineering College","t":"Suspicious"},
  {"code":"3923","name":"MNSK College of Engineering","t":"Avoid"},
  {"code":"3926","name":"Chendhuran College of Engineering and Technology","t":"Avoid"},
  {"code":"4020","name":"Anna University Regional Campus - Tirunelveli","t":"Transparent"},
  {"code":"4023","name":"University College of Engineering","t":"Transparent"},
  {"code":"4024","name":"University V.O.C. College of Engineering","t":"Transparent"},
  {"code":"4669","name":"Thamirabharani Engineering College (Autonomous)","t":"Avoid"},
  {"code":"4670","name":"Rohini College of Engineering & Technology","t":"Transparent"},
  {"code":"4672","name":"Stella Mary's College of Engineering","t":"Transparent"},
  {"code":"4675","name":"Universal College of Engineering and Technology","t":"Transparent"},
  {"code":"4676","name":"Renganayagi Varatharaj College of Engineering","t":"Avoid"},
  {"code":"4677","name":"Arunachala Hitech Engineering College (formerly Lourdes Mount College of Engineering and Technology)","t":"Avoid"},
  {"code":"4678","name":"Ramco Institute of Technology","t":"Transparent"},
  {"code":"4680","name":"AAA College of Engineering and Technology","t":"Suspicious"},
  {"code":"4686","name":"Good Shepherd College of Engineering and Technology","t":"Avoid"},
  {"code":"4864","name":"V V College of Engineering","t":"Transparent"},
  {"code":"4917","name":"Sethu Institute of Technology (Autonomous)","t":"Transparent"},
  {"code":"4925","name":"Sun College of Engineering and Technology","t":"Avoid"},
  {"code":"4927","name":"Maria College of Engineering and Technology","t":"Avoid"},
  {"code":"4928","name":"MAR Ephraem College of Engineering & Technology","t":"Avoid"},
  {"code":"4929","name":"M.E.T. Engineering College","t":"Avoid"},
  {"code":"4931","name":"Grace College of Engineering","t":"Transparent"},
  {"code":"4932","name":"Immanuel Arasar J.J. College of Engineering","t":"Avoid"},
  {"code":"4933","name":"St. Mother Theresa Engineering College","t":"Transparent"},
  {"code":"4934","name":"Holy Cross Engineering College","t":"Avoid"},
  {"code":"4937","name":"A.R College of Engineering and Technology","t":"Avoid"},
  {"code":"4938","name":"Sivaji College of Engineering and Technology","t":"Avoid"},
  {"code":"4941","name":"Unnamalai Institute of Technology","t":"Suspicious"},
  {"code":"4943","name":"Satyam College of Engineering and Technology","t":"Avoid"},
  {"code":"4944","name":"Arunachala College of Engineering for Women","t":"Transparent"},
  {"code":"4945","name":"Vins Christian Women's College of Engineering","t":"Avoid"},
  {"code":"4946","name":"D M I Engineering College","t":"Transparent"},
  {"code":"4948","name":"Rajas Institute of Technology","t":"Avoid"},
  {"code":"4949","name":"PSN Institute of Technology and Science","t":"Suspicious"},
  {"code":"4952","name":"C.S.I. Institute of Technology","t":"Transparent"},
  {"code":"4953","name":"Cape Institute of Technology","t":"Suspicious"},
  {"code":"4954","name":"Dr Sivanthi aditanar College of Engineering","t":"Transparent"},
  {"code":"4955","name":"Francis Xavier Engineering College (Autonomous)","t":"Transparent"},
  {"code":"4956","name":"Jayamatha Engineering College","t":"Avoid"},
  {"code":"4957","name":"Jayaraj Annapackiam CSI College of Engineering","t":"Suspicious"},
  {"code":"4959","name":"Kamaraj College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"4960","name":"Mepco Schlenk Engineering College (Autonomous)","t":"Transparent"},
  {"code":"4961","name":"Nellai College of Engineering (Formerly National College of Engineering)","t":"Avoid"},
  {"code":"4962","name":"National Engineering College (Autonomous)","t":"Suspicious"},
  {"code":"4964","name":"PSN College of Engineering and  Technology (Autonomous) Melathediyoor  Tirunelveli-627 152","t":"Avoid"},
  {"code":"4965","name":"P.S.R. Engineering College (Autonomous)","t":"Transparent"},
  {"code":"4966","name":"PET Engineering College","t":"Avoid"},
  {"code":"4967","name":"S. Veerasamy Chettiar College of Engineering and Technology","t":"Avoid"},
  {"code":"4968","name":"Sardar Raja College of Engineering","t":"Avoid"},
  {"code":"4969","name":"SCAD College of Engineering and Technology","t":"Suspicious"},
  {"code":"4970","name":"Sree Sowdambika College of Engineering","t":"Transparent"},
  {"code":"4971","name":"St. Xavier's Catholic College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"4972","name":"AMRITA College of Engineering and Technology","t":"Avoid"},
  {"code":"4974","name":"Government College of Engineering","t":"Transparent"},
  {"code":"4975","name":"Dr G.U. Pope College of Engineering","t":"Transparent"},
  {"code":"4976","name":"Infant Jesus College of Engineering","t":"Suspicious"},
  {"code":"4977","name":"Narayanaguru College of Engineering","t":"Avoid"},
  {"code":"4978","name":"Udaya School of Engineering","t":"Avoid"},
  {"code":"4979","name":"Arul Tharum VPMM College of Engineering and Technology (Formerly V.P.Muthaiah Pillai Meenakshi Ammal Engineering College for Women)","t":"Avoid"},
  {"code":"4980","name":"Einstein College of Engineering","t":"Avoid"},
  {"code":"4981","name":"Ponjesly College of Engineering","t":"Suspicious"},
  {"code":"4982","name":"Vins Christian College of Engineering","t":"Transparent"},
  {"code":"4983","name":"Lord Jegannath College of Engineering and Technology","t":"Avoid"},
  {"code":"4984","name":"MARTHANDAM COLLEGE OF ENGINEERING AND TECHNOLOGY","t":"Suspicious"},
  {"code":"4986","name":"Noorul Islam College of Engineering and Technology","t":"Avoid"},
  {"code":"4989","name":"PSN Engineering College","t":"Suspicious"},
  {"code":"4992","name":"Bethlahem Institute of Engineering","t":"Suspicious"},
  {"code":"4993","name":"Loyola Institute of Technology and Science","t":"Transparent"},
  {"code":"4994","name":"J.P. College of Engineering","t":"Transparent"},
  {"code":"4995","name":"P.S.R.R College of Engineering (Formerly P S R Rengasamy College of Engineering for Women)","t":"Suspicious"},
  {"code":"4996","name":"Sri Vidya College of Engineering and Technology","t":"Avoid"},
  {"code":"4998","name":"Mahakavi Bharathiyar College of Engineering and Technology","t":"Suspicious"},
  {"code":"4999","name":"Annai Vailankanni College of Engineering","t":"Avoid"},
  {"code":"5008","name":"Thiagarajar College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"5009","name":"Government College of Engineering","t":"Transparent"},
  {"code":"5010","name":"Anna University Regional Campus - Madurai","t":"Transparent"},
  {"code":"5012","name":"Central Electrochemical Research Institute CECRI)","t":"Avoid"},
  {"code":"5017","name":"University College of Engineering","t":"Transparent"},
  {"code":"5022","name":"University College of Engineering","t":"Transparent"},
  {"code":"5502","name":"Sri Raajaraajan College of Engineering and Technology","t":"Avoid"},
  {"code":"5530","name":"SSM Institute of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"5532","name":"Vaigai College of Engineering","t":"Avoid"},
  {"code":"5533","name":"Karaikudi Institute of Technology and Karaikudi Institute of Management","t":"Avoid"},
  {"code":"5536","name":"Mangayarkarasi College of Engineering","t":"Transparent"},
  {"code":"5537","name":"Jainee College of Engineering and Technology","t":"Avoid"},
  {"code":"5545","name":"G.T.N COLLEGE OF TECHNOLOGY","t":"Avoid"},
  {"code":"5546","name":"Jamal Mohamed College of Engineering","t":"Avoid"},
  {"code":"5703","name":"Christian College of Engineering and Technology","t":"Avoid"},
  {"code":"5720","name":"Sri Subramanya College of Engineering and Technology","t":"Avoid"},
  {"code":"5832","name":"N.P.R College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"5842","name":"SRM Madurai College for Engineering and Technology (Formely Madurai Institute of Engineering and Technology)","t":"Avoid"},
  {"code":"5851","name":"Veerammal Engineering College","t":"Avoid"},
  {"code":"5862","name":"RVS School of Engineering and Technology","t":"Avoid"},
  {"code":"5865","name":"Nadar Saraswathi College of Engineering and Technology","t":"Transparent"},
  {"code":"5901","name":"Alagappa Chettair Government College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"5902","name":"Bharath Niketan Engineering College","t":"Avoid"},
  {"code":"5904","name":"K.L.N.College of Engineering (Autonomous)","t":"Transparent"},
  {"code":"5907","name":"Mohamed Sathak Engineering College (Autonomous)","t":"Transparent"},
  {"code":"5910","name":"PSNA College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"5911","name":"P.T.R. College of Engineering and Technology","t":"Avoid"},
  {"code":"5912","name":"Pandian Saraswathi Yadav Engineering College","t":"Avoid"},
  {"code":"5913","name":"R.V.S. College of Engineering","t":"Avoid"},
  {"code":"5914","name":"Solamalai College of Engineering  (Autonomous)","t":"Transparent"},
  {"code":"5915","name":"SACS M.A.V.M.M. Engineering College","t":"Avoid"},
  {"code":"5919","name":"St. Michael College of Engineering and Technology","t":"Transparent"},
  {"code":"5921","name":"Syed Ammal Engineering College (Autonomous)","t":"Transparent"},
  {"code":"5924","name":"Ganapathy Chettiar College of Engineering and Technology","t":"Avoid"},
  {"code":"5930","name":"SBM College of Engineering and Technology","t":"Avoid"},
  {"code":"5935","name":"Fatima Michael College of Engineering and Technology","t":"Transparent"},
  {"code":"5942","name":"Ultra College of Engineering and Technology","t":"Avoid"},
  {"code":"5986","name":"Velammal College of Engineering and Technology (Autonomous)","t":"Transparent"},
  {"code":"5988","name":"Theni Kammavar Sangam College of Technology","t":"Transparent"},
  {"code":"5990","name":"Latha Mathavan Engineering College","t":"Transparent"},
  {"code":"null","name":"Sathyabama Institute of Science and Technology","t":"Suspicious"}
]
